name: $(Build.BuildId)_$(Date:yyyyMMdd)_$(Rev:.r)
trigger:
  branches:
    include:
    - develop

stages:

- stage: dockerLegacyStage
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - script: git checkout develop
    - script: ls ./containers -a
    - script: ls ./containers/docker -a
    - task: DockerCompose@0
      displayName: Build
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Owlvey Docker Connection'
        dockerComposeFile: './containers/docker/docker-compose.yaml'
        action: 'Build docker'
        qualifyImageNames: true
        additionalImageTags: 'V0.0.$(Build.BuildId)'

    - task: DockerCompose@0
      displayName: Publish
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Owlvey Docker Connection'
        dockerComposeFile: './containers/docker/docker-compose.yaml'
        action: Push services
        qualifyImageNames: true
        includeLatestTag: true
        additionalImageTags: 'V0.0.$(Build.BuildId)'
